### ISSUE TITLE
it is better to use the official openresty/lua-nginx-module directly

### ISSUE THREAD

**Issue by lziest** [bobrik/zoidberg-nginx#11]
Instead of using chaoslawful/lua-nginx-module, which will be redirected to openresty

**Comment by bobrik** [comment]
The plan is to use `balancer_by_lua` [from openresty](https://github.com/openresty/lua-nginx-module/tree/balancer-by-lua) and switch to vanilla openresty in docker image.

**Comment by lziest** [comment]
nice, I was going to suggest that next.

**Comment by bobrik** [comment]
#12
